apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - role: controller # with "+worker" if you want the node to be visable via kubectl, it will on default have a taint (NoSchedule)
    ssh:
      address: x.x.x.x # replace with the controller's IP address
      user: userx # Replace with requierd user (example "ubuntu" for ubuntu machines) 
      keyPath: ~/.ssh/id_rsa # key path on host system used to provision cluster
  - role: worker
    ssh:
      address: x.x.x.x # replace with the worker's IP address
      user: userx # Replace with requierd user (example "ubuntu" for ubuntu machines) 
      keyPath: ~/.ssh/id_rsa # key path on host system used to provision cluster
  - role: worker
    ssh:
      address: x.x.x.x # replace with the worker's IP address
      user: userx # Replace with requierd user (example "ubuntu" for ubuntu machines) 
      keyPath: ~/.ssh/id_rsa # key path on host system used to provision cluster
k0s:
  config:
    spec:
      network:
        provider: calico # Calico was used in this example, but support for others exist
        calico:
          mode: vxlan  # or 'ipip' depending on your network requirements
          overlay: Always  # or 'CrossSubnet' or 'Never'
          mtu: 1500  # adjust based on your network MTU
          wireguard: false  # set to true if you want WireGuard encryption
